### ISSUE TITLE
Reading secrets from Parameter Store is giving AccessDeniedException

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-workshop-for-kubernetes#250]
Reading secrets from AWS Parameter Store is giving AccessDeniedException. This is in spite of the fact that the key can be used from the worker nodes IAM role.

This is a follow up from https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/119.

```
  Exception in thread "main" com.amazonaws.services.simplesystemsmanagement.model.AWSSimpleSystemsManagementException: User: arn:aws:sts::091144949931:assumed-role/nodes.example.cluster.k8s.local/i-05101c6ca462115a9 is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:091144949931:parameter/GREETING (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: AccessDeniedException; Request ID: d8a3e20a-d17f-11e7-a11d-5323541cf7d1)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
  at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.doInvoke(AWSSimpleSystemsManagementClient.java:6495)
  at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.invoke(AWSSimpleSystemsManagementClient.java:6471)
  at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.executeGetParameter(AWSSimpleSystemsManagementClient.java:3955)
  at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.getParameter(AWSSimpleSystemsManagementClient.java:3931)
  at org.examples.java.App.getSecret(App.java:25)
  at org.examples.java.App.main(App.java:16)
```

**Comment by MCLDG** [comment]
Fixed by PR#251
