### ISSUE TITLE
Failed with Vault secret pod.

### ISSUE THREAD

**Issue by vishalcloudyuga** [aws-samples/aws-workshop-for-kubernetes#318]
- I have tried this example with minikube and also with the cluster created using the kubeadm but it gives same error.

Vault status.
```
$ vault status

Type: shamir
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce: 
Version: 0.9.0
Cluster Name: vault-cluster-346f87fe
Cluster ID: 06bfd3f6-9371-d170-f927-4c2d208f4cba

High-Availability Enabled: false

```
I followed instruction as mentioned in your AWS-workshop course.
When i deploy a Pod using secrets from Vault. It shows error.
```
$ kubectl get pods --show-all
NAME               READY     STATUS    RESTARTS   AGE
vault-kubernetes   0/1       Error     0          9s
```

The logs look like.
```
$ kubectl logs vault-kubernetes

serviceToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InZhdWx0LWF1dGgtdG9rZW4tNGR6amwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidmF1bHQtYXV0aCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImM1ZmZjYTc3LWU3YTMtMTFlNy1hZmI0LTA2MTE4Zjg3MzVjMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnZhdWx0LWF1dGgifQ.L643fpHEibTWjOtv-HFYwblibhAg1qT6vLZYqAHo1OLx5iTBZw1X26epi9X0eYo2VHLS8iOc82F6SyBTl4cWGyksvfX1L4tDxs7La1gf9EkwR_RCfOaWouiqz0E9vPCrjtJWePX3bTcaW00vFvgX4BIOMzJtOBWq83oBH5Hpqahvq9kLDkreYT8Vl5bgnm7QREYyd6riRJeUKMyzTHq7VXR2pwNfGYifW3S3v4FHBFSwHYACEl3-zMwsbjegLzod9zOT1CNFAvxI2r9odoMIfwpB97ZmBUqXKGLF8-_JEoS--h-68G--N-Zdmtv0M2fq8YAB6Ex184NdZn8sy2HyqQ
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: --> POST http://104.131.44.74:8200/v1/auth/kubernetes/login
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json; charset=utf-8
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: Content-Length: 895
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: 
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: {
    "role": "demo",
    "jwt": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InZhdWx0LWF1dGgtdG9rZW4tNGR6amwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidmF1bHQtYXV0aCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImM1ZmZjYTc3LWU3YTMtMTFlNy1hZmI0LTA2MTE4Zjg3MzVjMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnZhdWx0LWF1dGgifQ.L643fpHEibTWjOtv-HFYwblibhAg1qT6vLZYqAHo1OLx5iTBZw1X26epi9X0eYo2VHLS8iOc82F6SyBTl4cWGyksvfX1L4tDxs7La1gf9EkwR_RCfOaWouiqz0E9vPCrjtJWePX3bTcaW00vFvgX4BIOMzJtOBWq83oBH5Hpqahvq9kLDkreYT8Vl5bgnm7QREYyd6riRJeUKMyzTHq7VXR2pwNfGYifW3S3v4FHBFSwHYACEl3-zMwsbjegLzod9zOT1CNFAvxI2r9odoMIfwpB97ZmBUqXKGLF8-_JEoS--h-68G--N-Zdmtv0M2fq8YAB6Ex184NdZn8sy2HyqQ"
}
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: --> END POST (895-byte body)
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: <-- 500 Internal Server Error http://104.131.44.74:8200/v1/auth/kubernetes/login (111ms)
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: Cache-Control: no-store
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: Date: Sat, 23 Dec 2017 06:14:26 GMT
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: Content-Length: 401
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: 
Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: {"errors":["{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"tokenreviews.authentication.k8s.io is forbidden: User \\\"system:serviceaccount:default:vault-auth\\\" cannot create tokenreviews.authentication.k8s.io at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"group\":\"authentication.k8s.io\",\"kind\":\"tokenreviews\"},\"code\":403}"]}

Dec 23, 2017 6:14:26 AM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (401-byte body)
Exception in thread "main" org.json.JSONException: JSONObject["auth"] not found.
	at org.json.JSONObject.get(JSONObject.java:520)
	at org.json.JSONObject.getJSONObject(JSONObject.java:732)
	at org.examples.java.App.getClientToken(App.java:85)
	at org.examples.java.App.main(App.java:26)

```

**Comment by vishalcloudyuga** [comment]
I have to update some RBAC rules then it worked
